### PR TITLE
fixed all paths to be os independent

### LINKED ISSUE #146: make paths os independent

### PR DESCRIPTION
**Pull request by crapStone**
closes #146

### CODE REVIEW

File: src-tauri/src/config/handler.rs [hunk 1]
```diff
@@ -56,7 +57,7 @@ pub fn write_config(config: TomlConfig) -> Result<()> {
 
 pub fn get_hazard_symbols() -> Result<GHSSymbols> {
   // symbols from: https://unece.org/transportdangerous-goods/ghs-pictograms
-  let symbol_folder = get_program_path().with_file_name("ghs_symbols");
+  let symbol_folder = PathBuf::from(env::args().next().unwrap()).with_file_name("ghs_symbols");
```
Comment (crapStone) [inline src-tauri/src/config/handler.rs:60]: fix hardcoded path

**Review by Epsilon02 — APPROVED** [review]

**Review by 6543 — APPROVED** [review]
