### PR TITLE
clean up alertservice and component, fixed weird alert behavior

### LINKED ISSUE #205: [UI] snackbar: If multible errors are triggerd, they just get append to existing snackbar
If you trigger an error with in the timelimit an existing error are displayed via snackbar, you get it just appended ...

Bildschirmfoto zu 2021-03-01 02-22-59

introduced with  #177

### PR DESCRIPTION
**Pull request by Epsilon02**
fixes #205

### CODE REVIEW

File: src/app/alertsnackbar/alertsnackbar.component.ts [hunk 1]
```diff
@@ -1,151 +1,77 @@
...
+
+        this.alerts.push(alert);
+
+        if (!this.snackBarVisible) {
+          this.snackBarVisible = true;
+          this.openSnackBar()
+            ?.afterDismissed()
+            .subscribe(
+              () => {
+                this.snackBarVisible = false;
```
Comment (crapStone) [inline src/app/alertsnackbar/alertsnackbar.component.ts:40]: this would show only two per call

**Review by crapStone — CHANGES_REQUESTED** [review]

**Review by crapStone — DISMISSED** [review]

**Review by crapStone — APPROVED** [review]
